alias v = ^$env.EDITOR
alias l = ls
alias la = ls -a
alias ll = ls -l
alias lla = ls -la
alias lal = ls -la
alias fg = job unfreeze
alias g = ^git
alias gs = ^git status -s
alias gss = ^git status
alias gd = ^git diff
alias gdc = ^git diff --cached
alias gl = ^git log --graph --full-history --all --abbrev-commit
alias glp = ^git log --graph --oneline --patch --ext-diff
alias glt = ^git log --graph --full-history --all --oneline --simplify-by-decoration
alias ga = ^git add
alias gaa = ^git add -A
alias gc = ^git commit
alias gcm = ^git commit -m
alias gca = ^git commit -a
alias gcam = ^git commit -am
alias gcn = ^git commit --amend
alias gp = ^git push
alias gpl = ^git pull
