set -g default-terminal "screen"
set -g status-keys emacs
set -g mode-keys   emacs
set  -g mouse on
set  -g focus-events on
setw -g aggressive-resize on
setw -g clock-mode-style 24
set  -s escape-time 0
set  -g history-limit 5000
new-session -A -s 0

# unbind default prefix
unbind C-b
set -g prefix None

# hide bar[
# set -g status off 

# allow passthrough so nvim can display images in terminal emulator
set -g allow-passthrough on

bind -n M-t new-window
bind -n M-Tab previous-window
bind -n M-BTab next-window

bind -n M-c kill-pane
bind -n M-f resize-pane -Z

bind -n M-v split-window -h -c "#{pane_current_path}"
bind -n M-s split-window -v -c "#{pane_current_path}"

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-H resize-pane -L 4
bind -n M-J resize-pane -D 4
bind -n M-K resize-pane -U 4
bind -n M-L resize-pane -R 4

bind -n M-: command-prompt

setw -g mode-keys vi
bind -n M-y copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
