set -g default-terminal "screen-256color"
set -g status-keys emacs
set -g mode-keys   emacs
set -g mouse on
set -g focus-events on
setw -g aggressive-resize on
setw -g clock-mode-style 24
set -s escape-time 0
set -g history-limit 5000
set -g destroy-unattached on

# unbind default prefix
unbind C-b
set -g prefix None

# show bar only while a pane or window exists
set -g status off
set -g @dynamic_status 'if-shell \
    "[ #{session_windows} -gt 1 ] || [ #{window_panes} -gt 1 ] || [ #{window_zoomed_flag} -eq 1 ]" \
    "set status on" \
    "set status off"'
set-hook -g window-layout-changed "#{@dynamic_status}"
set-hook -g after-resize-pane "#{@dynamic_status}"

# allow passthrough so programs can can display images in terminal emulator
set -g allow-passthrough on

# idempotent create/switch windows
set -g base-index 1
set -g pane-base-index 1
bind -n M-1 if-shell "tmux select-window -t :1" "" "new-window -t :1"
bind -n M-2 if-shell "tmux select-window -t :2" "" "new-window -t :2"
bind -n M-3 if-shell "tmux select-window -t :3" "" "new-window -t :3"
bind -n M-4 if-shell "tmux select-window -t :4" "" "new-window -t :4"
bind -n M-5 if-shell "tmux select-window -t :5" "" "new-window -t :5"
bind -n M-6 if-shell "tmux select-window -t :6" "" "new-window -t :6"
bind -n M-7 if-shell "tmux select-window -t :7" "" "new-window -t :7"
bind -n M-8 if-shell "tmux select-window -t :8" "" "new-window -t :8"
bind -n M-9 if-shell "tmux select-window -t :9" "" "new-window -t :9"

bind -n M-: command-prompt
bind -n M-z detach-client
bind -n M-p paste-buffer

bind -n M-f resize-pane -Z
bind -n M-c kill-pane
bind -n M-v split-window -h -c "#{pane_current_path}"
bind -n M-s split-window -v -c "#{pane_current_path}"
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
bind -n M-H swap-pane -t '{left-of}'
bind -n M-J swap-pane -t '{down-of}'
bind -n M-K swap-pane -t '{up-of}'
bind -n M-L swap-pane -t '{right-of}'
bind -n C-M-h resize-pane -L 4
bind -n C-M-j resize-pane -D 4
bind -n C-M-k resize-pane -U 4
bind -n C-M-l resize-pane -R 4

setw -g mode-keys vi
bind -n M-y copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind -T copy-mode-vi C-[ send-keys -X cancel
